name: TotemGuard
version: ${version}
main: de.outdev.totemguard.TotemGuard
api-version: '1.20'
authors: [OutDev, Asleepp]
description: A plugin specifically designed to detect players using the 'AutoTotem' hack.
commands:
  totemguard:
    aliases: tg
    description: Main plugin command used to reload the plugin.

  check:
    aliases: totemcheck, checktotem
    description: Checks a player for manually for AutoTotem.
