name: TotemGuardV2
version: '${project.version}'
main: de.outdev.totemguardv2.TotemGuardV2
api-version: '1.20'
authors: [OutDev, Asleepp]
description: A plugin specifically designed to detect players using the 'AutoTotem' hack.
commands:
  totemguard:
    permission: op
