name: TotemGuard
version: ${version}
main: com.strealex.totemguard.TotemGuard
api-version: '1.20'
authors: [ Bram, OutDev, Asleepp ]
description: A plugin specifically designed to detect players using the 'AutoTotem' hack.
load: POSTWORLD
libraries:
  - de.exlll:configlib-yaml:${configlibVersion}
  - de.exlll:configlib-paper:${configlibVersion}
depend:
  - packetevents
  - CommandAPI
commands:
  Check:
    description: Checks a player for manually for AutoTotem.
    permission: TotemGuard.Check
    permission-message: Unknown command. Type "/help" for help
    aliases:
      - totemcheck
      - checktotem
permissions:
  TotemGuard.Alerts:
    description: Allows the player to use /totemguard alerts.
    default: op
  TotemGuard.Reload:
    description: Allows the player to use /totemguard reload.
    default: op
  TotemGuard.Check:
    description: Allows the player to use the /check command.
    default: op
