name: TotemGuard
version: ${version}
main: net.strealex.totemguard.TotemGuard
api-version: '1.20'
authors: [ Bram, OutDev, Asleepp ]
description: A plugin specifically designed to detect players using the 'AutoTotem' hack.
load: POSTWORLD
libraries:
  - de.exlll:configlib-yaml:${configlibVersion}
  - de.exlll:configlib-paper:${configlibVersion}
depend:
  - packetevents
permissions:
  TotemGuard.*:
    description: Gives access to all TotemGuard permissions.
    default: op
    children:
      TotemGuard.Reload: true
      TotemGuard.Alerts: true
      TotemGuard.Alerts.Others: true
      TotemGuard.Check: true
  TotemGuard.Alerts:
    description: Allows the player to use /totemguard alerts.
    default: op
  TotemGuard.Alerts.Others:
    description: Allows the player to use /totemguard alerts <player>.
    default: op
  TotemGuard.Reload:
    description: Allows the player to use /totemguard reload.
    default: op
  TotemGuard.Check:
    description: Allows the player to use the /check command.
    default: op
commands:
  TotemGuard:
    description: Base command for TotemGuard.
    aliases:
      - tg
  Check:
    description: Checks a player for manually for AutoTotem.
    aliases:
      - totemcheck
      - checktotem
