[versions]
paper-api = "1.20.4-R0.1-SNAPSHOT"
packetevents = "2.4.0"
lombok = "1.18.34"
configlib = "4.5.0"
shadow = "8.3.0"
run-paper = "2.3.0"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
packetevents-spigot = { group = "com.github.retrooper", name = "packetevents-spigot", version.ref = "packetevents" }
configlib-yaml = { group = "de.exlll", name = "configlib-yaml", version.ref = "configlib" }
configlib-paper = { group = "de.exlll", name = "configlib-paper", version.ref = "configlib" }

[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }